{@pullPubMed==1}?{
  IF OBJECT_ID('@tableName', 'U') IS NOT NULL
  DROP TABLE @tableName;

  CREATE TABLE @tableName (
      MESH_CODE VARCHAR(50),
      MESH_NAME VARCHAR(500),
      MESH_TYPE VARCHAR(50),
      PMID      INT
  );

  ALTER TABLE @tableName OWNER TO RW_GRP;
}

{@summarizeStart==1}?{
  IF OBJECT_ID('@tableName','U') IS NOT NULL
  DROP TABLE @tableName;

  CREATE TABLE @tableName (
    ID SERIAL,
  	SOURCE_ID	VARCHAR(20),
  	SOURCE_CODE_1	VARCHAR(50),
  	SOURCE_CODE_TYPE_1	VARCHAR(55),
  	SOURCE_CODE_NAME_1	VARCHAR(255),
  	RELATIONSHIP_ID	VARCHAR(20),
  	SOURCE_CODE_2	VARCHAR(50),
  	SOURCE_CODE_TYPE_2	VARCHAR(55),
  	SOURCE_CODE_NAME_2	VARCHAR(255),
  	UNIQUE_IDENTIFIER	VARCHAR(50),
  	UNIQUE_IDENTIFIER_TYPE	VARCHAR(50),
    DISTINCT_PMID_COUNT INT
  );

  ALTER TABLE @tableName OWNER TO RW_GRP;
}

{@summarize==1}?{
  WITH CTE_PAIRS AS (
  	SELECT *
  	FROM (
  		SELECT DISTINCT MESH_CODE AS DRUG_MESH_CODE, MESH_NAME AS DRUG_MESH_NAME
  		FROM @tableNameForPrep
  		WHERE UPPER(MESH_TYPE) = 'DRUG'
  		AND MESH_CODE = '@drug'
  	) z
  	CROSS JOIN (
  		SELECT DISTINCT MESH_CODE AS CONDITION_MESH_CODE, MESH_NAME AS CONDITION_MESH_NAME
  		FROM @tableNameForPrep
  		WHERE UPPER(MESH_TYPE) = 'CONDITION'
  		--AND MESH_CODE = '@condition'
  	) x
  )
  INSERT INTO @tableName (SOURCE_ID, SOURCE_CODE_1, SOURCE_CODE_TYPE_1, SOURCE_CODE_NAME_1,
  	RELATIONSHIP_ID, SOURCE_CODE_2, SOURCE_CODE_TYPE_2, SOURCE_CODE_NAME_2,
  	UNIQUE_IDENTIFIER, UNIQUE_IDENTIFIER_TYPE, DISTINCT_PMID_COUNT)
  SELECT DISTINCT
  	'MEDLINE_PUBMED' AS SOURCE_ID,
  	p.DRUG_MESH_CODE AS SOURCE_CODE_1,
  	'MeSH' AS SOURCE_CODE_TYPE_1,
  	p.DRUG_MESH_NAME AS SOURCE_CODE_NAME_1,
  	'Co-Occurrence' AS RELATIONSHIP_ID,
  	p.CONDITION_MESH_CODE AS SOURCE_CODE_2,
  	'MeSH' AS SOURCE_CODE_TYPE_2,
  	p.CONDITION_MESH_NAME AS SOURCE_CODE_NAME_2,
  	p.DRUG_MESH_CODE +'-'+ p.CONDITION_MESH_CODE AS UNIQUE_IDENTIFIER,
  	'DRUG_MESH_CODE-CONDITION_MESH_CODE' AS UNIQUE_IDENTIFIER_TYPE,
  	COUNT(DISTINCT c.PMID) AS DISTINCT_PMID_COUNT
  FROM CTE_PAIRS p
  	LEFT OUTER JOIN @tableNameForPrep d
  		ON d.MESH_CODE = p.DRUG_MESH_CODE
  	LEFT OUTER JOIN @tableNameForPrep c
  		ON c.MESH_CODE = p.CONDITION_MESH_CODE
  		AND c.PMID = d.PMID
  GROUP BY p.DRUG_MESH_CODE, p.DRUG_MESH_NAME, p.CONDITION_MESH_CODE, p.CONDITION_MESH_NAME;
}
