IF OBJECT_ID('@tableName', 'U') IS NOT NULL DROP TABLE @tableName;

CREATE TABLE @tableName (
  SOURCE_ID VARCHAR(20),
  DESCRIPTION VARCHAR(1000),
  PROVENANCE VARCHAR(20),
  CONTRIBUTOR_ORGANIZATION  VARCHAR(100),
  CONTACT_NAME VARCHAR(50),
  CREATION_DATE DATE,
  COVERAGE_START_DATE DATE,
  COVERAGE_END_DATE DATE,
  VERSION_IDENTIFIER  VARCHAR(50)
);
