set search_path = staging_umls;

CREATE INDEX X_MRCONSO_CODE ON MRCONSO(CODE);
CREATE INDEX X_MRCONSO_CUI ON MRCONSO(CUI);
CREATE INDEX X_MRCONSO_LUI ON MRCONSO(LUI);
CREATE UNIQUE INDEX X_MRCONSO_PK ON MRCONSO(AUI);
CREATE INDEX X_MRCONSO_SAB_TTY ON MRCONSO(SAB, TTY);
CREATE INDEX X_MRCONSO_SCUI ON MRCONSO(SCUI);
CREATE INDEX X_MRCONSO_SDUI ON MRCONSO(SDUI);
CREATE INDEX X_MRCONSO_STR ON MRCONSO(STR);
CREATE INDEX X_MRCONSO_SUI ON MRCONSO(SUI);
ALTER TABLE MRCONSO ADD CONSTRAINT X_MRCONSO_PK PRIMARY KEY USING INDEX X_MRCONSO_PK;