set search_path = staging_umls;

ALTER TABLE MRCONSO DROP CONSTRAINT IF EXISTS X_MRCONSO_PK;
DROP INDEX IF EXISTS X_MRCONSO_CODE;
DROP INDEX IF EXISTS  X_MRCONSO_CUI;
DROP INDEX IF EXISTS  X_MRCONSO_LUI;
DROP INDEX IF EXISTS  X_MRCONSO_PK;
DROP INDEX IF EXISTS  X_MRCONSO_SAB_TTY;
DROP INDEX IF EXISTS  X_MRCONSO_SCUI;
DROP INDEX IF EXISTS  X_MRCONSO_SDUI;
DROP INDEX IF EXISTS  X_MRCONSO_STR;
DROP INDEX IF EXISTS  X_MRCONSO_SUI;
