select CASE WHEN o.OUTCOME_OF_INTEREST_CONCEPT_ID IS NULL THEN 0 ELSE 1 END NEGATIVE_CONTROL,
  d.*
FROM @summaryData d
  LEFT OUTER JOIN @summaryOptimizedData o
    ON d.OUTCOME_OF_INTEREST_CONCEPT_ID = o.OUTCOME_OF_INTEREST_CONCEPT_ID
{@outcomeOfInterest='condition'}?{
  WHERE d.OUTCOME_OF_INTEREST_CONCEPT_ID IN (
    SELECT CONCEPT_ID FROM @vocabulary.CONCEPT WHERE DOMAIN_ID = 'Drug' AND CONCEPT_CLASS_ID = 'Ingredient'
  )
}
ORDER BY 1 DESC, PERSON_COUNT_DC DESC, PERSON_COUNT_RC DESC, OUTCOME_OF_INTEREST_CONCEPT_NAME
