{@outcomeOfInterest == 'condition'}?{
  /*Find conditions after exposure to drug*/
  /*Drug is first exposure*/
  WITH CTE_INDEX AS (
  	SELECT PERSON_ID, MIN(de.DRUG_EXPOSURE_START_DATE) AS INDEX_DRUG
  	FROM @schemaRaw.DRUG_EXPOSURE de
  	WHERE DRUG_CONCEPT_ID IN (
  		SELECT DESCENDANT_CONCEPT_ID FROM @schemaRaw.CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID IN (@conceptsOfInterest)
  	)
  	GROUP BY PERSON_ID
  )
  SELECT c1.CONCEPT_ID, c1.CONCEPT_NAME,
  	COUNT_BIG(DISTINCT co.PERSON_ID) AS PERSON_COUNT
  FROM @schemaRaw.CONCEPT c1
  	JOIN @schemaRaw.CONCEPT_ANCESTOR ca1
  		ON ca1.ANCESTOR_CONCEPT_ID = c1.CONCEPT_ID
  	JOIN @schemaRaw.CONCEPT c2
  		ON c2.CONCEPT_ID = ca1.DESCENDANT_CONCEPT_ID
  	JOIN @schemaRaw.CONDITION_OCCURRENCE co
  		ON co.CONDITION_CONCEPT_ID = ca1.DESCENDANT_CONCEPT_ID
  	JOIN CTE_INDEX i
  		ON i.PERSON_ID = co.PERSON_ID
  		AND i.INDEX_DRUG <= co.CONDITION_START_DATE
  	JOIN @schemaRaw.OBSERVATION_PERIOD op
  		ON op.PERSON_ID = i.PERSON_ID
  		AND i.INDEX_DRUG BETWEEN op.OBSERVATION_PERIOD_START_DATE AND op.OBSERVATION_PERIOD_END_DATE
  		AND DATEDIFF(dd,op.OBSERVATION_PERIOD_START_DATE,i.INDEX_DRUG) >= 180
  WHERE UPPER(c1.DOMAIN_ID) = 'CONDITION'
  AND c1.STANDARD_CONCEPT = 'S'
  GROUP BY c1.CONCEPT_ID, c1.CONCEPT_NAME
  HAVING COUNT_BIG(DISTINCT co.PERSON_ID) >= @filter
  ORDER BY COUNT_BIG(DISTINCT co.PERSON_ID) DESC;
}

{@outcomeOfInterest == 'drug'}?{
  /*Find drugs after condition*/
  /*Condition is first exposure*/
  WITH CTE_INDEX AS (
  	SELECT PERSON_ID, MIN(de.CONDITION_START_DATE) AS CONCEPT_INDEX
  	FROM @schemaRaw.CONDITION_OCCURRENCE de
  	WHERE CONDITION_CONCEPT_ID IN (
  		SELECT DESCENDANT_CONCEPT_ID FROM @schemaRaw.CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID IN (@conceptsOfInterest)
  	)
  	GROUP BY PERSON_ID
  )
  SELECT c1.CONCEPT_ID, c1.CONCEPT_NAME, c1.CONCEPT_CLASS_ID,
  	COUNT_BIG(DISTINCT co.PERSON_ID) AS PERSON_COUNT
  FROM @schemaRaw.CONCEPT c1
  	JOIN @schemaRaw.CONCEPT_ANCESTOR ca1
  		ON ca1.ANCESTOR_CONCEPT_ID = c1.CONCEPT_ID
  	JOIN @schemaRaw.CONCEPT c2
  		ON c2.CONCEPT_ID = ca1.DESCENDANT_CONCEPT_ID
  	JOIN @schemaRaw.DRUG_EXPOSURE co
  		ON co.DRUG_CONCEPT_ID = ca1.DESCENDANT_CONCEPT_ID
  	JOIN CTE_INDEX i
  		ON i.PERSON_ID = co.PERSON_ID
  		AND i.CONCEPT_INDEX <= co.DRUG_EXPOSURE_START_DATE
  	JOIN @schemaRaw.OBSERVATION_PERIOD op
  		ON op.PERSON_ID = i.PERSON_ID
  		AND i.CONCEPT_INDEX BETWEEN op.OBSERVATION_PERIOD_START_DATE AND op.OBSERVATION_PERIOD_END_DATE
  		AND DATEDIFF(dd,op.OBSERVATION_PERIOD_START_DATE,i.CONCEPT_INDEX) >= 180
  WHERE UPPER(c1.DOMAIN_ID) = 'DRUG'
  AND c1.STANDARD_CONCEPT = 'S'
  GROUP BY c1.CONCEPT_ID, c1.CONCEPT_NAME, c1.CONCEPT_CLASS_ID
  HAVING COUNT_BIG(DISTINCT co.PERSON_ID) >= @filter
  ORDER BY COUNT_BIG(DISTINCT co.PERSON_ID) DESC;
}
