IF OBJECT_ID('@storeData', 'U') IS NOT NULL DROP TABLE @storeData;

{@outcomeOfInterest == 'condition'}?{
  SELECT c3.CONCEPT_ID
  INTO @storeData
  FROM @vocabulary.CONCEPT c1
  	JOIN @vocabulary.CONCEPT_ANCESTOR ca1
  		ON ca1.ANCESTOR_CONCEPT_ID = c1.CONCEPT_ID
  	JOIN @vocabulary.CONCEPT c2
  		ON c2.CONCEPT_ID = ca1.DESCENDANT_CONCEPT_ID
  		AND UPPER(c2.DOMAIN_ID) = 'DRUG'
  		AND c2.CONCEPT_ID IN (
  			SELECT DESCENDANT_CONCEPT_ID FROM @vocabulary.CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID IN ( @conceptsOfInterest )
  		)
  	JOIN @vocabulary.CONCEPT_RELATIONSHIP cr1
    		ON cr1.CONCEPT_ID_1 = c1.CONCEPT_ID
    	JOIN @vocabulary.CONCEPT c3 /*Map Indications to SNOMED*/
    		ON c3.CONCEPT_ID = cr1.CONCEPT_ID_2
  		AND UPPER(c3.DOMAIN_ID) = 'CONDITION'
  		AND UPPER(c3.STANDARD_CONCEPT) = 'S'
  WHERE UPPER(c1.VOCABULARY_ID) IN ( 'INDICATION', 'IND / CI' )
  AND c1.INVALID_REASON IS NULL;
}

{@outcomeOfInterest == 'drug'}?{
  SELECT c4.CONCEPT_ID
  INTO @storeData
  FROM @vocabulary.CONCEPT c1
  	JOIN @vocabulary.CONCEPT_RELATIONSHIP cr1
  		ON cr1.CONCEPT_ID_1 = c1.CONCEPT_ID
  	JOIN @vocabulary.CONCEPT c2 /*Map Indications to SNOMED*/
  		ON c2.CONCEPT_ID = cr1.CONCEPT_ID_2
  		AND c2.CONCEPT_ID IN (
  			SELECT DESCENDANT_CONCEPT_ID FROM @vocabulary.CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID IN (@conceptsOfInterest)
  		)
  	JOIN @vocabulary.CONCEPT_ANCESTOR ca1
  		ON ca1.ANCESTOR_CONCEPT_ID = c1.CONCEPT_ID
  	JOIN @vocabulary.CONCEPT c3 /*DRUGS*/
  		ON c3.CONCEPT_ID = ca1.DESCENDANT_CONCEPT_ID
  		AND UPPER(c3.DOMAIN_ID) = 'DRUG'
  	JOIN @vocabulary.CONCEPT_ANCESTOR ca2
  		ON ca2.DESCENDANT_CONCEPT_ID = c3.CONCEPT_ID
  	JOIN @vocabulary.CONCEPT c4
  		ON c4.CONCEPT_ID = ca2.ANCESTOR_CONCEPT_ID
  		AND UPPER(c4.DOMAIN_ID) = 'DRUG'
  		AND c4.STANDARD_CONCEPT = 'S'
  WHERE c1.VOCABULARY_ID IN ( 'INDICATION', 'IND / CI' )
  AND c1.INVALID_REASON IS NULL;
}

CREATE INDEX IDX_R_AS_INDICATIONS_CONCEPT_ID ON @storeData (CONCEPT_ID);

ALTER TABLE @storeData OWNER TO RW_GRP;
