/*INSERT INTO @storeData (DATA_TYPE,MAPPING_TYPE,OUTCOME_OF_INTEREST_CONCEPT_ID, OUTCOME_OF_INTEREST_CONCEPT_NAME, SOURCE_CODE, SOURCE_CODE_NAME, UNIQUE_IDENTIFIER, UNIQUE_IDENTIFIER_TYPE)
SELECT DISTINCT
	s.DATA_TYPE,
	'DESCENDANT_ALL' AS MAPPING_TYPE,
	c.CONCEPT_ID AS OUTCOME_OF_INTREST_CONCEPT_ID,
	c.CONCEPT_NAME AS OUTCOME_OF_INTEREST_CONCEPT_NAME,
	NULL AS SOURCE_CODE,
	NULL AS SOURCE_CODE_NAME,
	NULL AS UNIQUE_IDENTIFIER,
	NULL AS UNIQUE_IDENTIFIER_TYPE
FROM @storeData s
	JOIN @vocabulary.CONCEPT_ANCESTOR ca
		ON ca.ANCESTOR_CONCEPT_ID = s.OUTCOME_OF_INTEREST_CONCEPT_ID
		AND s.MAPPING_TYPE = 'DESCENDANT'
	JOIN @vocabulary.CONCEPT  c
		ON c.CONCEPT_ID = ca.DESCENDANT_CONCEPT_ID
	JOIN @conceptUniverseData u
	  ON u.CONCEPT_ID = c.CONCEPT_ID;*/

CREATE INDEX IDX_R_OUTCOME_OF_INTEREST_CONCEPT_ID ON @storeData (OUTCOME_OF_INTEREST_CONCEPT_ID);

ALTER TABLE @storeData OWNER TO RW_GRP;

