SELECT 'CONDITION' AS MESH_TYPE,
	c2.CONCEPT_CODE AS MESH_SOURCE_CODE,
	c2.CONCEPT_NAME AS MESH_SOURCE_NAME,
	COUNT(DISTINCT PERSON_ID) AS RECORD_COUNT,
	'DISTINCT PERSON' AS RECORD_TYPE
FROM CONDITION_OCCURRENCE co
	JOIN CONCEPT c
		ON c.CONCEPT_ID = co.CONDITION_CONCEPT_ID
	JOIN CONCEPT_RELATIONSHIP cr
		ON cr.CONCEPT_ID_1 = c.CONCEPT_ID
	JOIN CONCEPT c2
		ON c2.CONCEPT_ID = cr.CONCEPT_ID_2
		AND c2.VOCABULARY_ID = 'MeSH'
		AND c2.INVALID_REASON IS NULL
WHERE YEAR(GETDATE())-2 = YEAR(CONDITION_START_DATE) /*year where you reliably have full year*/
GROUP BY c2.CONCEPT_CODE,c2.CONCEPT_NAME
HAVING COUNT(DISTINCT PERSON_ID) >= 100
UNION ALL
SELECT 'CONDITION' AS MESH_TYPE,
	c.CONCEPT_CODE AS MESH_SOURCE_CODE,
	c.CONCEPT_NAME AS MESH_SOURCE_NAME,
	0 AS RECORD_COUNT,
	'MANUALLY ADDED' AS RECORD_TYPE
FROM CONCEPT c
WHERE c.CONCEPT_CODE IN (
  	'D013405' /*SUICIDE*/,
		'D056486' /*Acute Liver Injury*/,
		'D003875' /*Drug Eruptions*/,
		'D020820' /*Dyskinesias*/
)
