IF OBJECT_ID('@tableName', 'U') IS NOT NULL DROP TABLE @tableName;

SELECT *
INTO @tableName
FROM @sourceTableName
WHERE CONCEPT_ID_1 IS NOT NULL
AND CONCEPT_ID_1 != 0
AND CONCEPT_ID_2 IS NOT NULL
AND CONCEPT_ID_2 != 0

CREATE INDEX IDX_@tableName_CONCEPT_ID_1_CONCEPT_ID_2 ON @tableName (CONCEPT_ID_1, CONCEPT_ID_2)
