/* replace any existing SPL_TO_STANDARD_DRUG code mappings in the STCM table */

DROP INDEX IF EXISTS {@targetDialect == "postgresql"} ? {@schema.}IDX_STCM_SOURCE_CODE {@targetDialect == "sql server"} ? {ON @fqTableName};

DELETE FROM @fqTableName where SOURCE_VOCABULARY_ID = 'SPL_TO_STANDARD_DRUG';

INSERT INTO @fqTableName (SOURCE_CODE, SOURCE_CONCEPT_ID, SOURCE_VOCABULARY_ID,
  SOURCE_CODE_DESCRIPTION, TARGET_CONCEPT_ID, TARGET_VOCABULARY_ID,
  VALID_START_DATE, VALID_END_DATE, INVALID_REASON)

  SELECT DISTINCT c.CONCEPT_CODE AS SOURCE_CODE,
  	c.CONCEPT_ID AS SOURCE_CONCEPT_ID,
  	'SPL_TO_STANDARD_DRUG' AS SOURCE_VOCABULARY_ID,
  	c.CONCEPT_NAME AS SOURCE_CODE_DESCRIPTION,
  	c2.CONCEPT_ID AS TARGET_CONCEPT_ID,
  	NULL AS TARGET_VOCABULARY_ID,
  	CAST('1970-01-01' AS DATE) AS VALID_START_DATE,
    CAST('2099-12-31' AS DATE) AS VALID_END_DATE,
  	NULL AS INVALID_REASON
  FROM @vocabulary.CONCEPT c
  	JOIN @vocabulary.CONCEPT_RELATIONSHIP cr
  		ON cr.CONCEPT_ID_2 = c.CONCEPT_ID
  	JOIN @vocabulary.CONCEPT c2
  		ON c2.CONCEPT_ID = cr.CONCEPT_ID_1
  		AND c2.STANDARD_CONCEPT = 'S'
  		AND c2.DOMAIN_ID = 'Drug'
  WHERE c.VOCABULARY_ID = 'SPL';

CREATE INDEX IDX_STCM_SOURCE_CODE ON @fqTableName (SOURCE_CODE);
