/* replace any existing MESHTO_STANDARD code mappings in the STCM table */

DROP INDEX IF EXISTS {@targetDialect == "postgresql"} ? {@schema.}IDX_STCM_SOURCE_CODE {@targetDialect == "sql server"} ? {ON @fqTableName};

DELETE FROM @fqTableName where SOURCE_VOCABULARY_ID = 'MESH_TO_STANDARD';

INSERT INTO @fqTableName (SOURCE_CODE, SOURCE_CONCEPT_ID, SOURCE_VOCABULARY_ID,
  SOURCE_CODE_DESCRIPTION, TARGET_CONCEPT_ID, TARGET_VOCABULARY_ID,
  VALID_START_DATE, VALID_END_DATE, INVALID_REASON)

  /* used in MEDLINE data feed translation */
  SELECT DISTINCT
    c1.CONCEPT_CODE AS SOURCE_CODE,
    c1.CONCEPT_ID AS SOURCE_CONCEPT_ID,
    'MESH_TO_STANDARD' AS SOURCE_VOCABULARY_ID,
    c1.CONCEPT_NAME AS SOURCE_CODE_DESCRIPTION,
    c2.CONCEPT_ID AS TARGET_CONCEPT_ID,
    NULL AS TARGET_VOCABULARY_ID,
  	CAST('1970-01-01' AS DATE) AS VALID_START_DATE,
    CAST('2099-12-31' AS DATE) AS VALID_END_DATE,
    NULL AS INVALID_REASON
  FROM @vocabulary.CONCEPT c1
  	JOIN @vocabulary.CONCEPT_RELATIONSHIP cr
  		ON cr.CONCEPT_ID_1 = c1.CONCEPT_ID
  		AND (
  			cr.INVALID_REASON IS NULL
  			OR cr.INVALID_REASON = ''
  		)
  	JOIN @vocabulary.CONCEPT c2
  		ON c2.CONCEPT_ID = cr.CONCEPT_ID_2
  		AND c2.DOMAIN_ID IN ('Condition','Drug')
  		AND c2.STANDARD_CONCEPT = 'S'
  WHERE UPPER(c1.VOCABULARY_ID) = 'MESH';

CREATE INDEX IDX_STCM_SOURCE_CODE ON @fqTableName (SOURCE_CODE);
