IF OBJECT_ID('@tableName','U') IS NOT NULL
DROP TABLE @tableName;

SELECT *
INTO @tableName
FROM (

  SELECT DISTINCT c.CONCEPT_CODE AS SOURCE_CODE,
  	c.CONCEPT_ID AS SOURCE_CONCEPT_ID,
  	'SPL_TO_STANDARD_DRUG' AS SOURCE_VOCABULARY_ID,
  	c.CONCEPT_NAME AS SOURCE_DESCRIPTION_ID,
  	c2.CONCEPT_ID AS TARGET_CONCEPT_ID,
  	NULL AS VALID_START_DATE,
  	NULL AS VALID_END_DATE,
  	NULL AS INVALID_REASON
  FROM @sourceSchema.dbo.CONCEPT c
  	JOIN @sourceSchema.dbo.CONCEPT_RELATIONSHIP cr
  		ON cr.CONCEPT_ID_2 = c.CONCEPT_ID
  	JOIN @sourceSchema.dbo.CONCEPT c2
  		ON c2.CONCEPT_ID = cr.CONCEPT_ID_1
  		AND c2.STANDARD_CONCEPT = 'S'
  		AND c2.DOMAIN_ID = 'Drug'
  WHERE c.VOCABULARY_ID = 'SPL'

) z

CREATE INDEX IDX_@tableName_SOURCE_CODE ON @tableName (SOURCE_CODE)
