IF OBJECT_ID('@tableName', 'U') IS NOT NULL DROP TABLE @tableName;

WITH CTE_VOCAB_1 AS (
	SELECT *
	FROM CEM.dbo.CEM_SOURCE_TO_CONCEPT_MAP
	WHERE SOURCE_VOCABULARY_ID = 'EUPLADR_TO_STANDARD'
),
CTE_VOCAB_2 AS (
	SELECT *
	FROM CEM.dbo.CEM_SOURCE_TO_CONCEPT_MAP
	WHERE SOURCE_VOCABULARY_ID = 'MEDDRA_TO_STANDARD'
)
SELECT ID,
      SOURCE_ID,
      SOURCE_CODE_1,
      SOURCE_CODE_TYPE_1,
      SOURCE_CODE_NAME_1,
      CASE WHEN v1.TARGET_CONCEPT_ID IS NULL THEN 0 ELSE v1.TARGET_CONCEPT_ID END CONCEPT_ID_1,
      RELATIONSHIP_ID,
      SOURCE_CODE_2,
      SOURCE_CODE_TYPE_2,
      SOURCE_CODE_NAME_2,
      CASE WHEN v2.TARGET_CONCEPT_ID IS NULL THEN 0 ELSE v2.TARGET_CONCEPT_ID END CONCEPT_ID_2,
      UNIQUE_IDENTIFIER,
      UNIQUE_IDENTIFIER_TYPE,
      SOC,
      HLGT,
      HLT,
      LLT,
      AGE_GROUP,
      GENDER,
      CAUSALITY,
      FREQUENCY,
      CLASS_WARNING,
      CLINICAL_TRIALS,
      POST_MARKETING,
      COMMENT
INTO @tableName
FROM @sourceTableName eu
	LEFT OUTER JOIN CTE_VOCAB_1 v1
		ON eu.SOURCE_CODE_1 = v1.SOURCE_CODE
	LEFT OUTER JOIN CTE_VOCAB_2 v2
		ON eu.SOURCE_CODE_2 = v2.SOURCE_CODE;

CREATE INDEX IDX_EUPLADR_CONCEPT_ID_1_CONCEPT_ID_2 ON @tableName (CONCEPT_ID_1, CONCEPT_ID_2);
