IF OBJECT_ID('@tableName','U') IS NOT NULL
DROP TABLE @tableName;

CREATE TABLE @tableName (
  ID INT IDENTITY(1,1) PRIMARY KEY,
	SOURCE_ID	VARCHAR(20),
	SOURCE_CODE_1	VARCHAR(50),
	SOURCE_CODE_TYPE_1	VARCHAR(55),
	SOURCE_CODE_NAME_1	VARCHAR(255),
	CONCEPT_ID_1	INT,
	RELATIONSHIP_ID	VARCHAR(20),
	SOURCE_CODE_2	VARCHAR(50),
	SOURCE_CODE_TYPE_2	VARCHAR(55),
	SOURCE_CODE_NAME_2	VARCHAR(255),
	CONCEPT_ID_2	INT,
	UNIQUE_IDENTIFIER	VARCHAR(50),
	UNIQUE_IDENTIFIER_TYPE	VARCHAR(50),
  PREDICATE VARCHAR(50),
  SUBJECT_SEMTYPE VARCHAR(50),
  SUBJECT_NOVELTY INT,
  OBJECT_NOVELTY  INT,
  SENTENCE_ID INT,
  TYPE  VARCHAR(5),
  NUMBER  INT,
  SENTENCE  VARCHAR(999),
  ISSN  VARCHAR(10),
  DP  VARCHAR(50),
  EDAT  VARCHAR(50),
  PYEAR INT
);

WITH CTE_UMLS_TO_VOCAB AS (
  /*~~~Right now created the lookup but once we have updated copy of UMLS
  should pull directly from there~~~*/
	SELECT *
	FROM CEM.dbo.LU_CUI_TO_OMOP_VOCAB
),
CTE_SEMMEDDB AS (
	SELECT PREDICATION_ID AS SOURCE_ID,
		SUBJECT_CUI AS SOURCE_CODE_1,
		'UMLS CUI' AS SOURCE_CODE_TYPE_1,
		SUBJECT_NAME AS SOURCE_CODE_NAME_1,
		PREDICATE AS RELATIONSHIP_TYPE_ID,
		OBJECT_CUI AS SOURCE_CODE_2,
		'UMLS CUI' AS SOURCE_CODE_TYPE_2,
		OBJECT_NAME AS SOURCE_CODE_NAME_2,
		p.PMID AS UNIQUE_IDENTIFIER,
		'PMID' AS UNIQUE_IDENTIFIER_TYPE,
		PREDICATE, SUBJECT_SEMTYPE, SUBJECT_NOVELTY,
		OBJECT_SEMTYPE, OBJECT_NOVELTY,
		p.SENTENCE_ID, TYPE, NUMBER, SENTENCE,
		ISSN, DP, EDAT, PYEAR
	FROM @sourceSchema.dbo.PREDICATION p
		LEFT OUTER JOIN @sourceSchema.dbo.SENTENCE s
			ON s.SENTENCE_ID = p.SENTENCE_ID
		LEFT OUTER JOIN @sourceSchema.dbo.CITATIONS c
			ON p.PMID = c.PMID
	WHERE PREDICATE IN (
		'CAUSES','AFFECTS','ASSOCIATED_WITH',
		'COMPLICATES','DISRUPTS','INHIBITS',
		'INTERACTS_WITH','PREDISPOSES','PREVENTS',
		'PRODUCES','STIMULATES','TREATS',

		'NEG_CAUSES','NEG_AFFECTS','NEG_ASSOCIATED_WITH',
		'NEG_COMPLICATES','NEG_DISRUPTS','NEG_INHIBITS',
		'NEG_INTERACTS_WITH','NEG_PREDISPOSES','NEG_PREVENTS',
		'NEG_PRODUCES','NEG_STIMULATES','NEG_TREATS'
	)
	AND SUBJECT_SEMTYPE IN (
		/*DRUGS*/
		'clnd', /*Clinical Drug*/
		'phsu', /*pharmaceutical substance*/
		'antb', /*Antibiotic*/
		'bacs', /*Biologically Active Substance*/
		'orch', /*organic chemical*/
		'inch', /*Inorganic Chemical*/
		'horm', /*Hormone*/
		'vita' /*Vitamin*/
	)
	AND OBJECT_SEMTYPE IN (
		/*CONDITIONS*/
		'cgab', /*Congenital Abnormality*/
		'dsyn', /*Disease or Syndrome*/
		'mobd', /*Mental or Behavioral Dysfunction*/
		'patf', /*Pathologic Function*/
		'inpo', /*Injury or Poisoning*/
		'sosy', /*Sign or Symptom*/
		'rich', /*Rickettsia or Chlamydia*/
		'acab'	/*Acquired Abnormality*/
	)
)
INSERT INTO @tableName (SOURCE_ID, SOURCE_CODE_1,
	SOURCE_CODE_TYPE_1, SOURCE_CODE_NAME_1, CONCEPT_ID_1, RELATIONSHIP_ID,
	SOURCE_CODE_2, SOURCE_CODE_TYPE_2,	SOURCE_CODE_NAME_2, CONCEPT_ID_2,
	UNIQUE_IDENTIFIER, UNIQUE_IDENTIFIER_TYPE, PREDICATE, SUBJECT_SEMTYPE,
	SUBJECT_NOVELTY, OBJECT_NOVELTY, SENTENCE_ID, TYPE, NUMBER, SENTENCE,
	ISSN, DP, EDAT, PYEAR)
SELECT SOURCE_ID,
	SOURCE_CODE_1,
	SOURCE_CODE_TYPE_1,
	SOURCE_CODE_NAME_1,
	v1.CONCEPT_ID AS CONCEPT_ID_1,
	RELATIONSHIP_TYPE_ID,
	SOURCE_CODE_2,
	SOURCE_CODE_TYPE_2,
	SOURCE_CODE_NAME_2,
	v2.CONCEPT_ID AS CONCEPT_ID_1,
	UNIQUE_IDENTIFIER,
	UNIQUE_IDENTIFIER_TYPE,
	PREDICATE,
	SUBJECT_SEMTYPE,
	SUBJECT_NOVELTY,
	OBJECT_NOVELTY,
	SENTENCE_ID,
	TYPE,
	NUMBER,
	SENTENCE,
	ISSN,
	DP,
	EDAT,
	PYEAR
FROM CTE_SEMMEDDB
	LEFT OUTER JOIN CTE_UMLS_TO_VOCAB v1
		ON v1.CUI = SOURCE_CODE_1
	LEFT OUTER JOIN CTE_UMLS_TO_VOCAB v2
		ON v2.CUI = SOURCE_CODE_2;

CREATE INDEX IDX_@tableName_UNIQUE_IDENTIFIER_CONCEPT_ID_1_CONCEPT_ID_2 ON @tableName (UNIQUE_IDENTIFIER, CONCEPT_ID_1, CONCEPT_ID_2);

