reinstall:
	#sudo R CMD REMOVE postProcessingEvidenceUnify
	R CMD build ../postProcessingEvidenceUnify
	sudo R CMD INSTALL postProcessingEvidenceUnify_0.1.0.tar.gz
	rm postProcessingEvidenceUnify_0.1.0.tar.gz
