IF OBJECT_ID('@targetTable', 'U') IS NOT NULL DROP TABLE @targetTable;

WITH CTE_VOCAB AS (
	SELECT *
	FROM @stcmTable
	WHERE UPPER(SOURCE_VOCABULARY_ID) = 'MEDDRA_TO_STANDARD'
)
SELECT ID,
      SOURCE_ID,
      SOURCE_CODE_1,
      SOURCE_CODE_TYPE_1,
      SOURCE_CODE_NAME_1,
      CONCEPT_ID_1,
      RELATIONSHIP_ID,
      SOURCE_CODE_2,
      SOURCE_CODE_TYPE_2,
      SOURCE_CODE_NAME_2,
      CASE WHEN stcm.TARGET_CONCEPT_ID IS NULL THEN 0 ELSE stcm.TARGET_CONCEPT_ID END AS CONCEPT_ID_2,
      UNIQUE_IDENTIFIER,
      UNIQUE_IDENTIFIER_TYPE,
      CASE_COUNT,
      PRR,
      PRR_95_PERCENT_LOWER_CONFIDENCE_LIMIT,
      PRR_95_PERCENT_UPPER_CONFIDENCE_LIMIT,
      ROR,
      ROR_95_PERCENT_LOWER_CONFIDENCE_LIMIT,
      ROR_95_PERCENT_UPPER_CONFIDENCE_LIMIT,
      COUNT_A,
      COUNT_B,
      COUNT_C,
      COUNT_D,
      CHI_SQUARE
INTO @targetTable
FROM @sourceTable a
	LEFT OUTER JOIN CTE_VOCAB stcm
		ON stcm.SOURCE_CONCEPT_ID = CAST(a.SOURCE_CODE_2 AS INT);

CREATE INDEX IDX_AEOLUS_TRANSLATED_CONCEPT_ID_1_CONCEPT_ID_2 ON @targetTable (CONCEPT_ID_1, CONCEPT_ID_2);

ALTER TABLE @targetTable OWNER TO RW_GRP;
